version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
      - "dependencies"
    groups:
      security-updates-github-actions:
        applies-to: security-updates
        patterns:
          - "*"
      minor-patch-github-actions:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain Gradle modules?
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "gradle"
      - "dependencies"
    groups:
      security-updates-gradle-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
      minor-patch-gradle-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Try and maintain the test consumer
  - package-ecosystem: "gradle"
    directory: "/test-consumers/compose"
    schedule:
      interval: "monthly"
    labels:
      - "test-consumer-compose"
      - "dependencies"
    groups:
      security-updates-test-consumer-compose:
        applies-to: security-updates
        patterns:
          - "*"
      minor-patch-test-consumer-compose:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain React bundles
  - package-ecosystem: "npm"
    directory: "/user-interface/authentication"
    schedule:
      interval: "monthly"
    labels:
      - "ui-authentication"
      - "dependencies"
    groups:
      security-updates-npm-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
      minor-patch-npm-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Monitor container images
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "docker"
      - "dependencies"
